### ISSUE TITLE
Ecore diagram editor shows import icons on inheritance arrows

### ISSUE THREAD

**Issue by dhendriks** [eclipse-ecoretools/ecoretools#7]
It looks something like this:

![img1](https://github.com/eclipse-ecoretools/ecoretools/assets/375606/c10c03b5-e1d5-4222-8e25-14ffd6e74f93)

You can see the import icon on the inheritance arrow in the left diagram. To reproduce:

* Create a new 'Ecore Modeling Project'. Name it `test`. Accept defaults.
* Create a new 'Ecore Model' in the same `model` directory, naming it `test2`.
* Name the package in `test2` also `test2`.
* Add a class diagram representation also for `test2`.
* Add a class named `Class1` to `test` using the diagram editor.
* Add a class named `Class2` to `test2` using the diagram editor.
* Save both diagrams.
* Add each class to the other diagram, using the 'Add' tool from the 'Existing Elements' part of the palette.
* Add an inheritance relation from one class to another, in one of the diagrams, using the 'SuperType' tool.
* Note how in one of the diagram the inheritance arrow shows with an import icon.

I get the import icon on imported classes, and find it useful. But it just looks weird an confusing on the arrow, in my opinion. Especially if you have a tree of inheritance relations, like this example from a metamodel in the Eclipse ESCET project:

![img2](https://github.com/eclipse-ecoretools/ecoretools/assets/375606/39ea8420-54b4-4f85-9ed7-48d773c43616)

(originally reported at: https://github.com/eclipse-emf/org.eclipse.emf/issues/12)

**Comment by pcdavid** [comment]
The corresponding decorator is [defined](https://github.com/eclipse-ecoretools/ecoretools/blob/master/org.eclipse.emf.ecoretools.design/description/ecore.odesign#L826C13-L826C13) to match any graphical element which represents a "remote" `EClassifier`. 

Because the inheritance edges correspond to a raw reference (and not a reified EObject), it is associated to its source `EClass`, so matches the condition.

I'll have to check, but I think the `preconditionExpression` on the decorator definition has access to enough information to exclude edges.
